language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh ./Scripts/travis_test.sh

    - os: osx
      osx_image: xcode9
      compiler: clang
      script:
        - sh ./Scripts/travis_test.sh

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ $TRAVIS_OS_NAME == linux ]; then 
       sudo apt-get update -qq;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
       brew update;
       wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz;
       tar xvf release-1.8.0.tar.gz;
       cd googletest-release-1.8.0;
       cmake .;
       sudo make -j $CPU_NUM install && cd ..;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)